try using R setup action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,14 +4,19 @@
 name: build
 
 on:
-
-  # we build artifacts on every push and release.
-  # on release events we additionally upload the artifacts to our RAN server
-
   push:
+    # we build/test all pushed branches, but not tags.
+    # we only push tags with releases, and we handle releases explicitly
+    branches:
+      - '**'
+    tags-ignore:
+      - '**'
+
+  pull_request:
+
   release:
     types:
-      - published
+      - 'published'
 
 jobs:
   build:
@@ -66,143 +71,11 @@ jobs:
           echo "R_MAJOR_VERSION=$R_MAJOR_VERSION" >> $GITHUB_ENV
           echo "R_MINOR_VERSION=$R_MINOR_VERSION" >> $GITHUB_ENV
 
-      - name: linux-env
-        if: ${{runner.os == 'Linux'}}
-        run: |
-          R_DIR="/usr/lib/R"
-          echo "R_DIR=$R_DIR" >> $GITHUB_ENV
-          echo "R=$R_DIR/bin/R" >> $GITHUB_ENV
-
-          R_LIBS=${GITHUB_WORKSPACE}/R_LIBS
-          mkdir -p $R_LIBS
-          echo "R_LIBS=$R_LIBS" >> $GITHUB_ENV
-
-      - name: linux-add-ubuntu-R-repos
-        if: ${{runner.os == 'Linux'}}
-        run: |
-          if [[ "$R_MAJOR_VERSION" == "4" ]]; then
-            CRAN_VERSION="40"
-          else
-            # 3.5 and 3.6 both use "35" repos...
-            CRAN_VERSION="35"
-          fi
-
-          # some version of R may already be installed on Github runners.
-          # remove it so we can install our desired version.
-          sudo apt-get -y remove r-*
-
-          echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran${CRAN_VERSION}/" | sudo tee /etc/apt/sources.list.d/rcran.list >> /dev/null
-          echo "deb-src https://cloud.r-project.org/bin/linux/ubuntu bionic-cran${CRAN_VERSION}/" | sudo tee -a /etc/apt/sources.list.d/rcran.list >> /dev/null
-          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
-
-      - name: linux-install-R
-        id: linux-install-R-from-package
-        if: ${{runner.os == 'Linux'}}
-        run: |
-          sudo apt-get -y update
-
-          INSTALLED=false
-          PKG_VERSION=$(apt-cache madison r-base | grep $R_VERSION | head -1 | cut -f2 -d"|" | xargs)
-          if [ -n "${PKG_VERSION}" ]; then
-            sudo apt-get -y install r-recommended=$PKG_VERSION r-base-core=$PKG_VERSION r-base=$PKG_VERSION 
-            if [ $? -eq 0 ]; then
-              INSTALLED=true
-            fi
-          fi
-
-      - name: mac-env
-        if: ${{runner.os == 'macOS'}}
-        run: |
-          R_LIBS=${GITHUB_WORKSPACE}/R_LIBS
-          mkdir -p $R_LIBS
-          echo "R_LIBS=$R_LIBS" >> $GITHUB_ENV
-          echo "R=R" >> $GITHUB_ENV
-
-          #          # downgrade gettext for better binary compatibility with older MacOS version (libintl.8.dylib)
-          #          brew unlink gettext
-          #          wget https://raw.githubusercontent.com/Homebrew/homebrew-core/d8d5099339909b5e5abf25449881257a27d829b9/Formula/gettext.rb
-          #          brew install gettext.rb
-
-      - name: mac-install-R
-        if: ${{runner.os == 'macOS'}}
-        run: |
-          # on macos we use a self-hosted runner with pre-installed versions of R
-          # in order to support older versions of MacOS (mojave) which aren't supported
-          # by GitHub. instead of installing R we swap between existing versions.
-
-          rm -rf /Library/Frameworks/R.framework/Versions/Current
-          ln -s /Library/Frameworks/R.framework/Versions/$R_MINOR_VERSION /Library/Frameworks/R.framework/Versions/Current
-
-          #R_INSTALLER_URL_BASE="https://cloud.r-project.org/bin/macosx/"
-          #if [[ "$R_MAJOR_VERSION" == "4" ]]; then
-          #  # for some reason R4 pkgs are under a /base subdir
-          #  R_INSTALLER_URL_BASE="$R_INSTALLER_URL_BASE/base/"
-          #fi
-
-          #R_INSTALLER_URL="$R_INSTALLER_URL_BASE${R_INSTALLER_FILE}"
-
-          #curl -O $R_INSTALLER_URL
-          #sudo installer -pkg $R_INSTALLER_FILE -target /
-
-      - name: windows-env
-        if: ${{runner.os == 'Windows'}}
-        shell: bash
-        run: |
-          # forward slashes easier to work with than double backslashes on windows...
-          R_LIBS=$(echo $GITHUB_WORKSPACE | sed 's/\\/\//g')/R_LIBS
-          mkdir -p $R_LIBS
-          echo "R_LIBS=$R_LIBS" >> $GITHUB_ENV
-
-          R_DIR="C:/R/R-${R_VERSION}"
-          R="$R_DIR/bin/R"
-          echo "R_DIR=$R_DIR" >> $GITHUB_ENV
-          echo "R=$R" >> $GITHUB_ENV
-
-          echo "TZ=UTC" >> $GITHUB_ENV
-
-      - name: windows-install-R
-        if: ${{runner.os == 'Windows'}}
-        shell: bash
-        run: |
-          R_INSTALLER_FILE="R-${R_VERSION}-win.exe"
-
-          # conveniently even the current version is available under "old"
-          R_INSTALLER_URL="https://cloud.r-project.org/bin/windows/base/old/${R_VERSION}/${R_INSTALLER_FILE}"
-
-          curl -O $R_INSTALLER_URL
-
-          if [ "$R_MAJOR_VERSION" == "4" ]
-          then
-            R_TOOLS_FILE="rtools40-x86_64.exe"
-            R_TOOLS_BIN="c:/rtools40/usr/bin"
-          else
-            # assume 3
-            R_TOOLS_FILE="Rtools35.exe"
-            R_TOOLS_BIN="c:/Rtools/bin"
-          fi
-
-          # rtools may already be installed on windows runners
-          if [ ! -d "$R_TOOLS_BIN" ]; then
-            curl -O "https://cran.r-project.org/bin/windows/Rtools/${R_TOOLS_FILE}"
-          fi
-
-          echo "R_INSTALLER_FILE=$R_INSTALLER_FILE" >> $GITHUB_ENV
-          echo "R_TOOLS_FILE=$R_TOOLS_FILE" >> $GITHUB_ENV
-          echo "R_TOOLS_BIN=$R_TOOLS_BIN" >> $GITHUB_ENV
-          echo "$R_TOOLS_BIN" >> $GITHUB_PATH
-
-      # installers are normally interactive, the /VERYSILENT flag will install non-interactive
-      # but is asynchronous so we use "start /wait" but that seems to be incompatible
-      # with the bash shell used here so we run these commands under a windows cmd shell.
-      - name: windows-install-R-cmd
-        if: ${{runner.os == 'Windows'}}
-        shell: cmd
-        run: |
-          start /wait %R_INSTALLER_FILE% /VERYSILENT /DIR="%R_DIR%"
-
-          IF NOT EXIST %R_TOOLS_BIN% (
-            start /wait %R_TOOLS_FILE% /VERYSILENT
-          )
+      - uses: actions/checkout@master
+      - name: Setup R
+        uses: r-lib/actions/setup-r@v1
+        with:
+          r-version: ${{ matrix.r }}
 
       - name: install-R-lib-deps
         shell: bash
@@ -359,3 +232,53 @@ jobs:
 
           curl -s https://raw.githubusercontent.com/Sage-Bionetworks/CI-Build-Tools/master/r-pkg/deploy.sh | bash
 
+  # on each of our matrix platforms, download the newly uploaded package from RAN
+  check-deploy:
+    needs: deploy
+
+    strategy:
+      matrix:
+        os: [ubuntu-18.04, macos-mojave, windows-2019]
+        r: [4.0.5, 4.1.0] 
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python }}
+
+      - name: check-pypi
+        shell: bash
+        run: |
+          if [[ "${{ github.event.release.prerelease}}" == "false" ]]; then
+            PYPI_INDEX_URL="https://pypi.org/simple/"
+          else
+            PYPI_INDEX_URL="https://test.pypi.org/simple/"
+          fi
+          RELEASE_TAG="${{ github.event.release.tag_name }}"
+          if [[ $RELEASE_TAG =~ ^v?([[:digit:]\.]+)(-rc)? ]]; then
+            VERSION="${BASH_REMATCH[1]}"
+            if [[ "${{ github.event.release.prerelease}}" == "true" ]]; then
+              VERSION="$VERSION.$GITHUB_RUN_NUMBER"
+            fi
+          else
+            echo "Unrecognized release tag"
+            exit 1
+          fi
+          # it can take some time for the packages to become available in pypi after uploading
+          for i in 5 10 20 40; do
+            if pip3 install --index-url $PYPI_INDEX_URL --extra-index-url https://pypi.org/simple "synapseclient==$VERSION"; then
+              ACTUAL_VERSION=$(synapse --version)
+              if [ -n "$(echo "$ACTUAL_VERSION" | grep -oF "$VERSION")" ]; then
+                echo "Successfully installed version $VERSION"
+                exit 0
+              else
+                echo "Expected version $VERSION, found $ACTUAL_VERSION instead"
+                exit 1
+              fi
+            fi
+            sleep $i
+          done
+          echo "Failed to install expected version $VERSION"
+          exit 1
